### ISSUE TITLE
TypeError: '>' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by gcapture** [databio/pepatac#84]
Hi all,
I'm trying to run the test example and have already run into some errors. 
Please see the log file attached. 
Not really sure how to proceed at this point, any help is appreciated. 
Thanks!

[PEPATAC_log.txt](https://github.com/databio/pepatac/files/2982709/PEPATAC_log.txt)

**Comment by nsheff** [comment]
I can't reproduce this. Looks like you're using a mac. I bet it has something to do with some mac quirkiness.

@michalstolarczyk can you try to reproduce this by just running pepatac on the test sample locally?

**Comment by michalstolarczyk** [comment]
It looks like the test run succeeded

[PEPATAC_log.txt](https://github.com/databio/pepatac/files/2983701/PEPATAC_log.txt)

**Comment by jpsmith5** [comment]
Look's like maybe a `python3` problem, as the pipeline requires 2 currently.  To confirm, try calling the pipeline directly using `python2`.

For example:
```
python2 pipelines/pepatac.py --single-or-paired paired \
  --prealignments rCRSd human_repeats \
  --genome hg38 \
  --sample-name test1 \
  --input examples/data/test1_r1.fastq.gz \
  --input2 examples/data/test1_r2.fastq.gz \
  --genome-size hs \
  -O $HOME/pepatac_test
```

The `YAMLLoadWarning` (line 50) is known and resolved in the latest updates to `pypiper`.  See databio/pypiper#128.

**Comment by nsheff** [comment]
confirmed, I was wrong about the mac thing, it's a python3 problem in pypiper.

```
> `gzip -d -c /home/nsheff/pepatac_test/test1/raw/test1_R1.fastq.gz > /home/nsheff/pepatac_test/test1/fastq/test1_R1.fastq`

<pre>
</pre>
Process 1100 returned: (0). Elapsed: 0:00:00. Peak memory: (Process: 0.001GB; Pipeline: 0.001GB)
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1427, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 556, in main
    container=pm.container)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 724, in run
    local_maxmem = max(local_maxmem, list_maxmem)
TypeError: unorderable types: list() > int()
Pipeline status: running
```

created issue: https://github.com/databio/pypiper/issues/133

**Comment by nsheff** [comment]
interesting that my error is slightly different, maybe because I'm using 3.6 instead of 3.7.

**Comment by gcapture** [comment]
Thanks all for all your help.
I called the pipeline with python2 (Python 2.7.15), it runs but fails at a certain point. 
I think the problem might be with pypiper/manager.py? I tried to reinstall pypiper but pipeline still fails.
Please find the log attached. Any thoughts?

[PEPATAC_log.txt](https://github.com/databio/pepatac/files/2987519/PEPATAC_log.txt)

**Comment by nsheff** [comment]
Hi @gcapture -- we've solved both your earlier problem (with python 3) and I *believe* also this problem with python 2 now. You need to:

- upgrade [pypiper](http://code.databio.org/pararead) to version `0.10` which I just released
- updgrade [pararead](http://code.databio.org/pararead) to `0.6`, which I just released.

Upgrade pepatac to `0.8.6` -- this should be [released later today](https://github.com/databio/pepatac/pull/89) by @jpsmith5.

Let us know if you run into further issues.

**Comment by gcapture** [comment]
Thanks @nsheff! That's good news.

I'll give the new versions a go.
